repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy  # This will not check python / r package...
-   repo: https://github.com/Quantco/pre-commit-mirrors-black
    rev: 23.1.0
    hooks:
    -   id: black-conda
        args:
        -   --safe
        -   --target-version=py38
-   repo: https://github.com/Quantco/pre-commit-mirrors-isort
    rev: '5.12.0'
    hooks:
    -   id: isort-conda
        additional_dependencies: [toml]
-   repo: https://github.com/Quantco/pre-commit-mirrors-flake8
    rev: 6.0.0
    hooks:
    -   id: flake8-conda
        args:
        -   --max-line-length=88
