# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_hdcdr_wrappers", use_symbols = TRUE, package_name = "hdcdr")

#' @docType package
#' @usage NULL
#' @useDynLib hdcdr, .registration = TRUE
NULL

hdcd_api <- function(X, method, segmentation) .Call(wrap__hdcd_api, X, method, segmentation)

