# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_hdcdr_wrappers", use_symbols = TRUE, package_name = "hdcdr")

#' @docType package
#' @usage NULL
#' @useDynLib hdcdr, .registration = TRUE
NULL

#' Find change points in a time series.
#' @param X Numerical matrix with time series.
#' @export
hdcd <- function(X) .Call(wrap__hdcd, X)

