# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_hdcdr_wrappers", use_symbols = TRUE, package_name = "hdcdr")

#' @docType package
#' @usage NULL
#' @useDynLib hdcdr, .registration = TRUE
NULL

#' Find change points in a time series.
#' @param X Numerical matrix with time series.
#' @param method Either 'knn' or 'change_in_mean'.
#' @param segmentation_type Either 'bs', 'sbs' or 'wbs'.
#' @export
hdcd <- function(X, method, segmentation_type) .Call(wrap__hdcd, X, method, segmentation_type)

