[package]
name = "hdcdpython"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = [ 'cdylib' ]

[dependencies]
numpy = "0.14.1"
hdcd = { path = "../" }
ndarray = "0.15.3"
pyo3 = {version = "0.14.5", features = ["extension-module"]}