[package]
name = "hdcd_py"
version = "0.1.0"
edition = "2018"

[lib]
name = "hdcd"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "hdcd"

[dependencies]
numpy = "0.14.1"
hdcd = { path = "../" }
ndarray = "0.15.3"
pyo3 = {version = "0.14.5", features = ["extension-module"]}